<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Saied Idris Baidhowi">
<meta name="dcterms.date" content="2023-01-20">

<title>Analisis Pengaruh Ekspor Besi Baja ke Negara Tiongkok Terhadap Nilai Tukar Rupiah Tahun 2012-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Ekspor Besi Baja ke Negara Tiongkok Terhadap Nilai Tukar Rupiah Tahun 2012-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Saied Idris Baidhowi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Perdagangan internasional merupakan aktivitas ekonomi yang melibatkan antara satu negara dengan negara lain. Kegiatan ini biasanya disebut ekspor impor. Suatu negara tentunya membutuhkan negara lain untuk memenuhi kebutuhan dari negaranya serta untuk memajukan negaranya. Kebijakan ekspor adalah jumlah konsumsi dalam negeri yang memenuhi kebutuhan dan jumlah produksi dalam negeri yang tercukupi. Konsumsi yaitu belanja barang-barang dan jasa-jasa yang dilakukan oleh rumah tangga dengan maksud memenuhi kebutuhannya (Sukirno, 2000). Proses pengolahan input menjadi output sehingga nilai barang tersebut bertambah merupakan pengertian dari produksi (Adiningsih, 1993). Dalam memenuhi kebutuhan yang krusial terhadap suatu komoditas yaitu salah satunya besi dan baja. Sebagai salah satu negara penghasil bijih nikel terbesar di dunia, Indonesia berkembang pesat dalam industri besi dan baja. Saat ini Indonesia menjadi negara penghasil besi dan baja stainless terbesar nomor dua di dunia. Peningkatan Produksi besi dan baja ini membuat Indonesia menjadi negara terbesar yang mengekspor besi dan baja ke Tiongkok.</p>
<p>Menurut laporan Badan Pusat Statistik (BPS), nilai ekspor besi dan baja nasional pada Januari-Desember 2021 mencapai US$ 21,47 miliar atau sekitar Rp 307,04 triliun. Nilai itu melonjak hingga 90,26% dibandingkan tahun sebelumnya, yaitu US$ 11,28 miliar atau sekitar Rp 161,13 triliun. Sedangkan, ekspor besi dan baja Indonesia mencapai 14,08 miliar kg. Volume ekspor tersebut naik 52,46% dibandingkan ekspor tahun sebelumnya sejumlah 9,24 miliar kg. Negara yang menjadi tujuan utama ekspor besi/baja Indonesia pada 2021 adalah Tiongkok yaitu dengan volume: 7.507.896.958 kg dan Nilai: US$ 12.818.414.216, Taiwan dengan volume: 1.735.849.217 kg&nbsp;dan Nilai: US$ 2.685.099.907 dan Malaysia dengan volume: 611.078.450 kg dan Nilai: US$ 745.508.509 (sumber : https://databoks.katadata.co.id)</p>
<p>Industri baja merupakan penggerak dari industri yang lain. Kemajuannya, tentunya dapat menjadi penguatan struktur industri lain di suatu negara. Melihat fenomena ini maka seharusnya pemerintah dapat memanfaatkannya dengan baik agar terus meningkatkan ekspor besi baja. Pemerintah juga harus memonitor hal ini. agar dengan meningkatnya ekspor ini tidak juga memberikan pasar impor yang tinggi untuk di dalam negeri. Nilai tukar suatu negara akan berpengaruh terhadap pertumbuhan ekspor. Nilai tukar yang semakin menguat akan berakibat pada jumlah ekspor suatu negara mengalami penurunan. Hal ini terjadi karena barang-barang di dalam negeri lebih mahal daripada barang luar negeri. begitupun sebaliknya. Dari latar belakang dan permasalahan diatas, maka penulis ingin meneliti tentang Pengaruh Ekspor Besi Baja ke Negara Tiongkok Terhadap Nilai Tukar Rupiah Tahun 2012-2021.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Obyek dari penelitian ini adalah ekspor besi/baja Indonesia ke Tiongkok, karena Tiongkok adalah importir besi baja terbesar dari Indonesia. Ruang lingkup penelitian ini adalah untuk mengenai pengaruh ekspor besi baja ke Tiongkok terhadap nilai tukar rupiah tahun 2012-2021 serta variabel - variabel yang berkaitan dengan judul penelitian yaitu ekspor dan nilai tukar rupiah. Data yang diambil dari badan pusat statistik selama sembilan tahun terakhir (2012-2021). Data ini kemudian dibandingkan dengan nilai tukar rupiah.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Dari pendahuluan yang sudah dikemukakan oleh penulis maka dapat didapatkan rumusan masalah sebagai berikut :</p>
<ol type="1">
<li>Menganalisis pengaruh ekspor besi dan baja ke negara Tiongkok terhadap nilai tukar rupiah tahun 2012-2021</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Berdasarkan masalah-masalah yang telah peneliti rumuskan, maka tujuan penelitian ini adalah untuk mendapatkan pengetahuan yang tepat (sahih, benar, valid) dan dapat dipercaya (dapat diandalkan, reliable) tentang pengaruh ekspor besi baja ke tiongkok terhadap nilai tukar rupiah. Manfaat yang diharapkan dari hasil penelitian ini adalah untuk mengetahui seberapa besar pengaruh ekspor besi/baja ke Tiongkok terhadap nilai tukar rupiah sebagai gambaran dan acuan dalam menetapkan kebijakan atau keputusan terhadap ekspor besi/baja ke Tiongkok.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Perdagangan Internasional</strong></p>
<p>Dua alasan utama negara-negara melakukan perdagangan internasional karena adanya perbedaan antar masing-masing negara serta agar produksi dapat mencapai skala ekonomis (economies of scale) (Krugman dan Obsfelt, 2003) perdagangan internasional memiliki subyek dalam ekonomi yaitu warga negara biasa, perusahaan ekspor, perusahaan impor, perusahaan industri, perusahaan negara, ataupun departemen pemerintah yang dapat dilihat dari neraca perdagangan (Sobri, 2000)</p>
<p><strong>Ekspor</strong></p>
<p>Ekspor merupakan penjualan dan pengeluaran barang dari dalam negeri ke luar negeri untuk suatu perekonomian. ekspor juga bisa dikatakan perdagangan dengan cara mengeluarkan barang dari dalam wilayah pabeanan indonesia ke luar negeri dengan memenuhi ketentuan yang berlaku. ekspor suatu negara dapar ditentukan oleh beberapa faktor seperti selera konsumen terhadap barang tersebut, harga barang tersebut dan kurs yang menentukan jumlah mata uang domestik</p>
<p><strong>Nilai Tukar</strong></p>
<p>Perdagangan antar negara dimana masing – masing negara mempunyai alat tukarnya sendiri mengharuskan adanya angka perbandingan nilai suatu mata uang dengan mata uang lainnya, yang disebut kurs valuta asing atau kurs (Salvatore, 1998)</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Nilai Ekspor (CNY)</th>
<th>Nilai Tukar (IDR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>364435820</td>
<td>815855480000</td>
</tr>
<tr class="even">
<td>2013</td>
<td>248602130</td>
<td>556540820000</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>446400010</td>
<td>999347140000</td>
</tr>
<tr class="even">
<td>2015</td>
<td>2143261960</td>
<td>4798079440000</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>6329532160</td>
<td>14169802240000</td>
</tr>
<tr class="even">
<td>2017</td>
<td>13898010630</td>
<td>31113209820000</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>17738134540</td>
<td>39710021560000</td>
</tr>
<tr class="even">
<td>2019</td>
<td>21105440230</td>
<td>47248344220000</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>51138203270</td>
<td>114482114780000</td>
</tr>
<tr class="even">
<td>2021</td>
<td>86707952170</td>
<td>194111429380000</td>
</tr>
</tbody>
</table>
<p><em>sumber data badan pusat statistik (FOB : USD 000)</em></p>
<p>Penelitian ini menggunakan data sekunder dalam bentuk time series dengan rentang waktu 2012-2021 berdasarkan nilai ekspor besi/baja Indonesia ke Tiongkok serta nilai tukar rupiah terhadap mata uang yuan Tiongkok.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"Nilai Ekspor"</span>,<span class="at">ylab=</span><span class="st">"Nilai Tukar"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-mpg-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Plot Nilai Ekspor Terhadap Nilai Tukar</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Nilai Tukar"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/fig1-mpg-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Plot Error Terhadap Nilai Tukar</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Teknik analisis yang digunakan yaitu deskriptif kuantitatif adalah suatu teknik yang bertujuan untuk membuat gambar atau deskriptif tentang suatu keadaan secara objektif yang menggunakan angka, mulai dari pengumpulan data, penafsiran terhadap data tersebut serta penampilan dan hasilnya (Arikunto, 2006). Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara nilai tukar dan nilai ekspor. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> Di mana <span class="math inline">\(y_t\)</span> adalah nilai tukar Yuan terhadap mata uang Rupiah. β0 adalah koefisien konstanta; β1 adalah parameter; <span class="math inline">\(x_t\)</span> adalah nilai ekspor dan μi adalah error term.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Nilai Ekspor</th>
<th>Pertumbuhan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>364435820</td>
<td>0</td>
</tr>
<tr class="even">
<td>2013</td>
<td>248602130</td>
<td>-0.32</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>446400010</td>
<td>0.80</td>
</tr>
<tr class="even">
<td>2015</td>
<td>2143261960</td>
<td>3.80</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>6329532160</td>
<td>1.95</td>
</tr>
<tr class="even">
<td>2017</td>
<td>13898010630</td>
<td>1.20</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>17738134540</td>
<td>0.28</td>
</tr>
<tr class="even">
<td>2019</td>
<td>21105440230</td>
<td>0.19</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>51138203270</td>
<td>1.42</td>
</tr>
<tr class="even">
<td>2021</td>
<td>86707952170</td>
<td>0.70</td>
</tr>
</tbody>
</table>
<p>Berdasarkan tabel di atas, pertumbuhan Nilai ekspor tahun 2012-2021 tumbuh secara fluktuatif. Pada tahun 2013 Nilai Ekspor besi baja Indonesia ke Tiongkok sempat mengalami minus sebesar -0.32% atau sebesar 248602130 hal tersebut mengalami penurunan dari tahun sebelumnya yaitu sebesar 364435820. Sedangkan pertumbuhan tertinggi nilai ekspor besi/baja Indonesia ke Tiongkok pada tahun 2015 yaitu sebesar 3.80% .</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil Pengaruh Ekspor Besi Baja ke Negara Tiongkok Terhadap Nilai Tukar Rupiah diestimasi menggunakan regresi univariat atau Ordinary Least Square (OLS). hasilnya ditunjukkan sebagai berikut :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in summary.lm(reg1): essentially perfect fit: summary may be unreliable</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0062720 -0.0032321 -0.0010537 -0.0001242  0.0119713 

Coefficients:
              Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept) -9.882e-03  2.250e-03 -4.391e+00  0.00231 ** 
X            2.239e+03  6.745e-14  3.319e+16  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.005694 on 8 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 1.102e+33 on 1 and 8 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Dapat dilihat dari tabel di atas bahwa hasil regresi jumlah ekspor besi/baja berpengaruh positif terhadap nilai tukar rupiah. Jumlah ekspor besi/baja meningkat sebesar 1 persen maka akan meningkatkan nilai tukar rupiah sebesar 4.467e-04. Apabila ekspor menurun sebesar 1 persen maka akan menurunkan nilai tukar rupiah sebesar 4.467e-04. hal ini menunjukkan bahwa ekspor besi baja berpengaruh terhadap nilai tukar rupiah. Ditunjukkann dengan di lihat dari probabilitas X (Nilai Ekspor) yang signifikan. nilai ekspor merupakan suatu faktor yang dapat dijadikan naik dan turunnya kurs mata uang suatu negara. Dengan hasil ini maka dapat disimpulkan bahwa pendapatan ekspor besi baja berpengaruh positif terhadap nilai tukar rupiah.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan data hasil analisis yang telah kami lakukan, setelah diamati ekspor besi/baja ke negara Tiongkok berpengaruh positif terhadap nilai tukar rupiah dan besi/baja merupakan salah satu komoditas utama yang memiliki volume ekspor tersebesar di Indonesia. Oleh sebab itu apabila ekspor besi/baja ke negara Tiongkok berpengaruh positif terhadap nilai tukar rupiah maka mempengaruhi nilai kurs rupiah terhadap yuan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Pradana, A. R. (2016). Faktor–Faktor yang Mempengaruhi Permintaan Impor Besi dan Baja di Indonesia dari Tiongkok Tahun 2000-2014. https://dspace.uii.ac.id/handle/123456789/32744</p>
<p>Nilai Ekspor Besi dan Baja Nasional Melesat 90,26% pada 2021, Tiongkok Jadi Tujuan Terbesar |Databoks. (n.d.). Retrieved January 20, 2023, from https://databoks.katadata.co.id/datapublish/2022/03/14/nilai-ekspor-besi-dan-baja-nasional-melesat-9026-pada-2021-tiongkok-jadi-tujuan-terbesar</p>
<p>Badan Pusat Statistik. (n.d.). Retrieved January 20, 2023, from https://www.bps.go.id/statictable/2019/02/27/2033/ekspor-besi-baja-menurut-negara-tujuan-utama-2012-2021.html</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>